# Generated by Django 4.1.4 on 2023-05-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение'),
        ),
    ]
