# Generated by Django 4.2.6 on 2023-10-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_formuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormUser',
        ),
    ]
