# Generated by Django 4.2.6 on 2023-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_formuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='ava.png', null=True, upload_to='product', verbose_name='Аватар'),
        ),
    ]
