# Generated by Django 4.2.6 on 2023-10-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_currentpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentPost',
        ),
    ]
