# Generated by Django 4.2 on 2023-07-17 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(11, message='номер введен не корректно'), django.core.validators.MaxLengthValidator(11, message='номер введен не корректно')], verbose_name='Номер телефона'),
        ),
    ]
