# Generated by Django 4.2 on 2023-07-19 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newform', '0003_remove_info_id_info_stud_id_alter_info_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='stud_id',
        ),
        migrations.AddField(
            model_name='info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000000, message='номер введен не корректно'), django.core.validators.MaxValueValidator(100000000000, message='номер введен не корректно')], verbose_name='Номер телефона'),
        ),
    ]
