# Generated by Django 4.2 on 2023-07-19 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newform', '0006_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(10000000000, message='номер введен не корректно'), django.core.validators.MaxValueValidator(100000000000, message='номер введен не корректно')], verbose_name='Номер телефона'),
        ),
    ]
