# Generated by Django 4.2 on 2023-07-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newform', '0007_alter_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
