# Generated by Django 4.1.4 on 2023-06-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('b', 'Рожок'), ('s', 'Стаканчик'), ('c', 'Шарик')], default='s', max_length=1, verbose_name='Вид')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
                'ordering': ['-published'],
            },
        ),
    ]
