# Generated by Django 4.1.4 on 2023-06-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, verbose_name='Номер')),
            ],
        ),
        migrations.AddField(
            model_name='ice',
            name='page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.page', verbose_name='Номер'),
        ),
    ]
